### ISSUE TITLE
Doesn't take all attendance

### ISSUE THREAD

**Issue by Satyajit-2003** [Titan1911/Google-Meet-Attendance-using-Python#3]
It is working fine but fails to take attendance when the list of participants need to scroll. It is just taking attendance of the first scroll screen

**Comment by Titan1911** [comment]
Sorry for the late reply. I didn't came across this kind of issue when i tested it. Can u please send the screenshots of the issue related. It would help me to solve the same.

**Comment by Satyajit-2003** [comment]
Well, I needed that at time of my online class, as it is not going on now, I may not be able to provide screenshot. And to explain the issue, in the participants list in Google meet, makes the panel scrollable if there are more participants than the screen can hold. The method which you called easily got the names which are in the panel at that time, but didn't scroll the frame to get names of others. And I would suggest you to test it on a meeting, having around 20-25 participants .

**Comment by Titan1911** [comment]
Google keeps updating and might have changed it's structure which my code interact with. Also, chromedriver new version has some issues due to which the code doesn't run as it should, so there are chances I would not be able to solve the problem but will surely try to and will let you know. Alternatively, if you want to take the attendance professionally then there are extentions available, you can try them till the time I solve the issue.
