### ISSUE TITLE
"This browser or app may not be secure" error

### ISSUE THREAD

**Issue by magbanum** [Titan1911/Google-Meet-Attendance-using-Python#5]
getting this error when I use my personal Gmail Id.

error:
Couldn't sign you in
This browser or app may not be secure.
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by Titan1911** [comment]
After reading your issue I tried running the code, but facing the same issue. Surely google has updated it's settings in the new version of chromedriver. I used to run it with the earlier version so it used to work fine but now it's not even allowing me to use the earlier version. Directly logging in is prohibited so I wrote code to login with stack overflow. In the new version they have solved this glitch and that's why the issue is arising. Still I have the last solution, it worked for me. Create a new gmail ID which dosen't have an account on stack overflow and then try it. But really not sure if this works for others or not. Alternatively, I can try logging in with any other site(except stack overflow) and if I get the required results, would let you know!
